config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users
  resources :users do
    member do
      get :hovercard
      get :past_events
      get :live_events
    end
  end
  resources :events do
    resources :invitations, only: [:new, :create]
  end
  get 'live_events', to: 'events#live'
  get 'past_events', to: 'events#past'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  has_many :invitations, foreign_key: "attended_event_id", dependent: :destroy
  has_many :attendess, through: :invitations, source: :attendee
  has_one_attached :cover_image, dependent: :destroy
  scope :past_events, -> {where("date < ?", Date.today).order("date DESC")}
  scope :live_events, -> {where("date >= ?", Date.today).order("date ASC")}
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :avatar, dependent: :destroy
  has_many :events, foreign_key: 'creator_id', dependent: :destroy
  has_many :invitations, foreign_key: 'attendee_id', dependent: :destroy
  has_many :attended_events, through: :invitations

  def past_events
    self.attended_events.past_events
  end

  def live_events
    self.attended_events.live_events
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception, prepend: true
  before_action :configure_permited_parameters, if: :devise_controller?


  protected

  def configure_permited_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:username, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :avatar]) 
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy]
  before_action :owner_only, only: %i[edit update destroy]

  def index
    @events = Event.all
  end

  def past
    @past_events = Event.past_events
  end

  def live
    @live_events = Event.live_events
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      redirect_to event_path(@event), notice: "Successfully created #{@event.name}"
    else
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    if @event.update_attributes(event_params)
      redirect_to event_path(@event)
    else
      render :edit
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def destroy
    @event.destory
    redirect_to events_path
  end

  private

  def owner_only
    @event = Event.find(params[:id])
    redirect_to events_path if current_user != @event.creator
  end

  def event_params
    params.require(:event).permit(:name, :description, :date, :location, :cover_image)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/invitations_controller.rb
# frozen_string_literal: true

class InvitationsController < ApplicationController
  before_action :authenticate_user
  before_action :registered, only: [:create]

  def new
    @invitation = Invitation.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @invitation = Invitation.new(invitation_params.merge(attendee: current_user, attended_event: @event))
    if @invitation.save
      redirect_to event_path(@event), notice: 'Thanks for registering'
    else
      render :new
    end
  end

  private

  def authenticate_user
    @event = Event.find(params[:event_id])

    unless current_user
      redirect_to event_path(@event), alert: 'You must be logged in'
    end
  end

  def registered
    if Invitation.exists?(attendee: current_user, attended_event: @event)
      redirect_to event_path(@event), alert: 'You are already registerd for this event'
    end
  end

  def invitation_params
    params.require(:invitation).permit(:accepted)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy hovercard]
  before_action :authenticate_user!, only: [:edit]
  def index
    @users = User.all
  end

  def hovercard
    render layout: false
  end

  def show; end

  def edit; end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private

  def user_params
    params.require(:user).permit(:username, :name, :avatar)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def user_avatar(user, size = 80)
    if user.avatar.attached?
      user.avatar.variant(resize_to_limit: [size, size])
    else
      gravatar_image_url(user.email, size: size)
    end
  end
  
  def event_cover_image(event, width=600 ,height = 300)
    if event.cover_image.attached?
      event.cover_image.variant(resize_to_limit: [width, height])
    else
      ActionController::Base.helpers.image_url('placeholder.jpg', width: width, height: height)
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_card_display.html.erb
  <div class="row row-cols-1 row-cols-sm-1 row-cols-md-3 row-cols-lg-4">
    <% events.each do |event| %>
      <div class='col-10 mb-4'>
        <div class='card p-3'>
          <%= image_tag event_cover_image(event, 700),  class: 'card-img-top', alt: 'cover_image' %>
          <div class="card-body">
            <h5 class="card-title"><%= event.name %></h5>

            <p class="card-text"><%= event.description %></p>
            <p class="card-text"><small class="text-muted">Last updated <%= time_ago_in_words(event.updated_at)%> ago</small></p>
            <%= link_to "#{ event.name }", event_path(event) %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

app/views/events/_event_display.html.erb
<% events.each do |event| %>
  <div class='col-10 mb-4'
       data-controller="eventcontent"
       data-action="mouseenter->eventcontent#shadow mouseleave->eventcontent#shadow"
       >
       <div class='card p-3'
            id="card-<%= event.id %>"
            data-target="eventcontent.card"
            >
            <%= image_tag event_cover_image(event,600, 300 ),  class: 'card-img-top', alt: 'cover_image' %>
         <div class="card-body">
           <h5 class="card-title"><%= event.name %></h5>

           <p class="card-text"><%= event.location %></p>
           <p class="card-text"><small class="text-muted">Last updated <%= time_ago_in_words(event.updated_at)%> ago</small></p>
           <%= link_to "#{ event.name }", event_path(event) %>
         </div>
       </div>
  </div>
<% end %>

app/views/events/_form.html.erb
<%= simple_form_for @event do |f| %>
<%= image_tag event_cover_image(@event,600, 300), width: '100%', height: 'auto'%>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :date %>
  <%= f.input :location %>
  <%= f.input :cover_image, as: :file %>
  <%= f.button :submit, "Create Event", class: 'btn btn-primary', id: 'create_event_btn' %>
<% end %>

app/views/events/_register_modal.html.erb
<div class="modal hide fade" id="register-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
    </div>
  </div>
</div>

app/views/events/edit.html.erb
<%= render 'form' %>

app/views/events/index.html.erb
<div class="container">
  <h1>Events</h1>
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <%= link_to "All Events", events_path, class: 'nav-link active' %>
    </li>
    <li class='nav-item'>
      <%= link_to 'Past Events', past_events_path, class: 'nav-link' %>
    </li>
    <li class='nav-item'>
      <%= link_to 'Live Events', live_events_path, class: 'nav-link' %>
    </li>
  </ul>
  <hr class="my-r">
  <div class="row row-cols-1 row-cold-xs-2 row-cols-md-3 row-cols-lg-4">
    <%= render partial: 'event_display', locals: {events:  @events}%>
  </div>
</div>

app/views/events/live.html.erb
<div class="container">
  <h1>Events</h1>
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <%= link_to "All Events", events_path, class: 'nav-link' %>
    </li>
    <li class='nav-item'>
      <%= link_to 'Past Events', past_events_path, class: 'nav-link' %>
    </li>
    <li class='nav-item'>
      <%= link_to 'Live Events', live_events_path, class: 'nav-link active' %>
    </li>
  </ul>
  <hr class="my-r">
  <div class="row row-cols-1 row-cold-xs-2 row-cols-md-3 row-cols-lg-4">
    <%= render partial: 'event_display', locals: {events:  @live_events}%>
  </div>
</div>

app/views/events/new.html.erb
<%= render 'form' %>

app/views/events/past.html.erb
<div class="container">
  <h1>Events</h1>
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <%= link_to "All Events", events_path, class: 'nav-link' %>
    </li>
    <li class='nav-item'>
      <%= link_to 'Past Events', past_events_path, class: 'nav-link active' %>
    </li>
    <li class='nav-item'>
      <%= link_to 'Live Events', live_events_path, class: 'nav-link' %>
    </li>
  </ul>
  <hr class="my-r">
  <div class="row row-cols-1 row-cold-xs-2 row-cols-md-3 row-cols-lg-4">
    <%= render partial: 'event_display', locals: {events:  @past_events}%>
  </div>
</div>

app/views/events/show.html.erb
<header class="event-listing__header ">
  <div class="listing-hero-image__blurry-background">
    <%= image_tag event_cover_image(@event), style: 'height:100%; width:auto;' %>
  </div>
</header>
<%# Event Listing Body %>
<div class='event-listing__body'>
  <%# Listing Hero Details%>
  <div class='listing-hero-details__main-container'>
    <div class="listing-hero_badge-container">
      <div class="row no-gutters" >
        <div class="col-8 listing-hero" >
          <div class='alignfull'>
            <%= image_tag event_cover_image(@event, 1080, 540),  class: 'img-fluid' %>
          </div>
        </div>
        <div class="col-4 d-flex flex-column p-4 listing-panel  justify-content-between">
          <div class='d-flex flex-column'>
            <div>
              <h5>
                <%= @event.date.to_date.strftime("%b")%>
              </h5>
            </div>
            <div>
              <h5>
                <%= @event.date.to_date.strftime("%d")%>
              </h5>
            </div>
          </div>
          <div>
            <h4>
              <%= @event.name %>
            </h4>
            <p class="text-muted">
            by <%= @event.creator.username %>
            </p>
          </div>
          <button class="btn btn-outline-primary">Follow</button>
          <p>Free</p>
        </div>
      </div>
    </div>
  </div>
  <div class='listing-body'>
    <%# Listing Card Panel%>
    <div class="listing-panel-wrapper row pt-2 pl-2 border-top border-bottom">
      <div class="col-8 d-flex flex-row">
        <i class="fa fa-share-square fa-2x m-2"></i>
        <i class="far fa-heart fa-2x m-2"></i>
           <% if @event.creator == current_user %>
            <%= link_to "Edit event", edit_event_path(@event), class: 'btn btn-caution' %> 
           <% end %>
      </div>
      <div class="col-2 d-flex flex-column">
        <%= link_to 'Register', new_event_invitation_path(@event),
          class:'btn btn-success', id: 'register-button',
          remote: true, data: { toggle: 'modal', target: '#register-modal'} 
        %>
          <%= render 'register_modal' %> 
      </div>
    </div>
    <%# Listing Card Info%>
    <div class="container listing-card-info">
      <div class="col-8">
        <section><%= @event.description %></section>
      </div>
      <div class="col-2">

      </div>
    </div>
    <div class="container p-5">
      <h2>Registered Users</h2>
      <hr class="my-r">
     <ul class="list-group p-2">
        <% @event.attendess.each do |attendee| %>
          <li class="list-group-item"><%= link_to attendee.username , attendee%></li>
          <% end %> 
      </ul> 
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="jumbotron">
  <h1 class="display-4 padding">Private Events</h1>
  <p class="lead">Plan and keep track of events with your friends</p>
  <hr class='my-r'>
  <p><strong>Demo Login: demo@example.com / password</strong></p>
  <% if user_signed_in? %>
    <%= link_to 'Events', events_path, class: 'btn btn-primary btn-lg' %>
  <% else %>
    <%= link_to 'Sign In', new_user_session_path, class: 'btn btn-primary btn-lg' %>
    <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-success btn-lg' %>
  <% end %>
</div>

app/views/invitations/_new.html.erb
<div class="modal-header">
  <h5 class="modal-title" id="exampleModalLabel"><%= @event.name %></h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<div class="modal-body">
  <%= simple_form_for [@event, @invitation] do |f| %>
    <%= f.input :accepted, as: :hidden, input_html: {value: true} %>
    <%= f.submit "Register", class: "btn btn-success" %>
  <% end %>
</div>
<div class="modal-footer">
</div>

app/views/invitations/new.js.erb
console.log('debug');
$("#register-modal").find(".modal-content").html('<%= j render partial: "invitations/new"  %>');

app/views/layouts/_footer.html.erb
<footer class="bg-primary pt-4 mt-4">
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="http://www.grantcottle.com/" class="text-light"> grantcottle.com</a>
  </div>
</footer>

app/views/layouts/_github.html.erb
<a href="https://github.com/grantmaster89/private_events" class="github-corner" aria-label="View source on GitHub"><svg width="80" height="80" viewBox="0 0 250 250" style="fill:#70B7FD; color:#fff; position: absolute; top: 0; border: 0; left: 0; transform: scale(-1, 1);" aria-hidden="true"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg></a><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>

app/views/layouts/_navbar.html.erb
<!-- Begin Bootstrap Navbar -->

<nav class="navbar navbar-expand-lg navbar-light bg-light shadow ">
  <a class="navbar-brand text-primary font-weight-bold" href="/">Private Events</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto align-items-center">
      <li class="nav-item active">
       <%= link_to "Home", root_path ,class: 'nav-link' %> 
      </li>
      <li class="nav-item">
        <%= link_to 'Events', events_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Members', users_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Invitations', '#', class: 'nav-link' %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <% if user_signed_in? %>
           <%= image_tag user_avatar(current_user, 20), class: 'img-fluid img-thumbnail'%>
           <% end %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if user_signed_in? %>
           <%= link_to 'Create Event', new_event_path, class: 'dropdown-item' %> 
          <div class="dropdown-divider"></div>
           <%= link_to current_user.username||'username', user_path(current_user), class: 'dropdown-item' %> 
           <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item' %> 
           <%= link_to 'Edit Profile', edit_user_registration_path, class: 'dropdown-item' %> 
          <% else %>
           <%= link_to 'Sign In', new_user_session_path, class: 'dropdown-item' %> 
           <%= link_to 'Sign Up', new_user_session_path, class: 'dropdown-item' %> 
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</nav>

<!-- End Bootstrap Navbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/github' %>

    <div class='container mt-5'>
      <%= yield %>
    </div>
    <%= render partial: "layouts/footer" %>
  </body>
</html>

app/views/users/edit.html.erb
<div class="row text-center justify-content-center">
  <div class='col-sm-5 my-5'>
    <%= simple_form_for(@user , class: 'form') do |f| %>
      <h2 class="h3 mb-3 font-weight-normal">Sign up</h2>
      <%= f.error_notification %>
      <div class="form-group">
        <div class="row">
          <div class="col-lg-4">
            <%= image_tag user_avatar(@user), class: 'img-fluid img-thumbnail'%>
          </div>

          <div class='col-lg-8'>
            <%= f.input :avatar,
              as: :file,
              input_html: { class: 'form-control m-2'} %>
          </div>
        </div>
      </div>
      <%= f.input :username,
        required: true,
        autofocus: true,
        label: false,
        input_html: { autocomplete: "username", class: "form-control m-2", placeholder: "Username" } %>

      <%= f.input :email,
        required: true,
        label: false,
        input_html: {autocomplete: "email", class: "form-control m-2", placeholder: "Email"} %>

      <%= f.button :submit, "Submit", class: "btn btn-lg btn-primary btn-block" %>
    <% end %>
  </div>
</div>

app/views/users/events.html.erb
<div data-action="click->eventcontent#live_events" data-target="eventcontent.content" class="row row-cols-1 row-cols-sm-1 row-cols-md-3 row-cols-lg-4">
    <% @events.each do |event| %>
      <div class='col-10 mb-4'>
        <div class='card p-3'>
          <%= image_tag event_cover_image(event, 700),  class: 'card-img-top', alt: 'cover_image' %>
          <div class="card-body">
            <h5 class="card-title"><%= event.name %></h5>

            <p class="card-text"><%= event.description %></p>
            <p class="card-text"><small class="text-muted">Last updated <%= time_ago_in_words(event.updated_at)%> ago</small></p>
            <%= link_to "#{ event.name }", event_path(event) %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

app/views/users/hovercard.html.erb
<div id="user-card-<%= @user.id%>" class="relative hidden" data-target="hovercard.card">
  <div data-tooltip-arrow class="absolute bottom-8 left-0 z-50 bg-white shadow-lg rounded-lg p-2 min-w-max-content">
    <div class="flex space-x-3 items-center w-64">
      <%= image_tag user_avatar(@user), class: "flex-shrink-0 h-24 w-24 object-cover border border-gray-200 bg-gray-100 rounded", alt: @user.email %>

      <div class="flex flex-col">
        <span class="text-sm leading-5 font-medium text-indigo-600">
          <%= @user.email %>
        </span>

        <span class="text-lg leading-0 font-semibold text-gray-900">
          <%= @user.username %>
        </span>

        <span class="flex text-sm text-gray-500">
          <%= @user.email %>
          <span class="mx-1">
            &middot;
          </span>
        </span>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="col-lg-4">
    <div class="card">
      <div class="card-body">
        <h3 class="card-title">Members</h3>
        <h6 class="card-subtitle mb-2 text-muted"></h6>
      </div>
    </div>
  </div>

  <div class="col-lg">
    <ul class="list-group">
      <% @users.each do |user| %>
        <li class="list-group-item">
          <div class="row">
            <div class="col-2">
              <%= image_tag user_avatar(user), class: 'img-fluid img-thumbnail'%>
            </div>
            <div class="col">
              <p><%= user.username %></p>
              <p><%= user.email %></p>
              <div>
                <%= link_to user.username, user , class: 'branded-link'%>
              </div>

            </div>
            <div class="col">
              <h6>Created Events (<%= user.events.count %>)</h4>
            </div>
          </div>

        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>